# Generated by Django 5.2.4 on 2026-05-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_wire_venture_relations'),
        ('users', '0001_bootstrap_member_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(
                blank=True,
                related_name='interested_users',
                to='projects.project',
                verbose_name='Избранные проекты',
            ),
        ),
    ]
